markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Browser Work
description: All about browsers.
keywords: Browser
url: http://www.browserwork.com
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: Aaron Zhang
    email: aaron.cheung@hotmail.com
    imageLink: https://avatars0.githubusercontent.com/u/3211768
    simpleIntro: Aaron Zhang - IE攻城狮
    detailIntro:
      <p>粗通浏览器实现，涉猎Webkit，Chrome，FireFox。闭门造车中，将摸索中心得记录下来，希望结识更多同道中人。</p>
#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/aaronzhcl
  - class: icon-github-alt
    url: http://github.com/aaronz
  - class: icon-facebook
    url: https://www.facebook.com/aaronzhcl
  - class: icon-linkedin
    url: http://www.linkedin.com/in/aaronzhcl
  - class: icon-google-plus
    url: https://plus.google.com/u/0/+AaronZhang-cl/

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-46083544-3

#comment config
disqus:
  config: false
  id: browserwork

duoshuo:
  config: true
  id: aaronzhcl