name: Browser Work
markdown: redcarpet
highlighter: pygments
paginate: 1
permalink: /:categories/:title
excerpt_separator: <!--more-->
production_url: http://www.browserwork.com
gems: [jekyll-paginate]
collections:
- tests